application: instaright
version: 17
runtime: python 
api_version: 1

handlers:
- url: /cron
  script: cron.py
#  login: admin

- url: /scripts
  static_dir: scripts

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
#  login: admin

- url: /visual
  script: visualization.py

- url: /stats
  script: stats.py

- url: /static
  static_dir: static

- url: /date_update
  script: cron.py

- url: /delete_stats
  script: stat_management.py

- url: /stats_task
  script: stat_management.py

- url: /data_consolidation
  script: data_consolidation.py

- url: /article/(.*)
  script: articles.py

- url: /feed
  script: articles.py

- url: /callback
  script: phbb_callback.py

- url: /memcache_test
  script: cron.py

- url: /_ah/xmpp/message/chat/
  script: xmpp_handler.py

- url: /.*
  script: main.py

inbound_services:
  - xmpp_message
