application: instaright
version: 12
runtime: python 
api_version: 1

handlers:
- url: /cron
  script: cron.py
#  login: admin

- url: /scripts
  static_dir: scripts

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
#  login: admin

- url: /visual
  script: visualization.py

- url: /stats
  script: stats.py

- url: /static
  static_dir: static

- url: /date_update
  script: cron.py

- url: /delete_stats
  script: stat_management.py

- url: /stats_task
  script: stat_management.py

- url: /data_consolidation
  script: data_consolidation.py

- url: /.*
  script: main.py

