application: instaright
version: 26
runtime: python 
api_version: 1

handlers:
- url: /cron
  script: cron.py
  login: admin

- url: /scripts
  static_dir: scripts

- url: /css
  static_dir: css

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /visual
  script: visualization.py

- url: /stats
  script: stats.py

- url: /static
  static_dir: static

- url: /date_update
  script: cron.py

- url: /delete_stats
  script: stat_management.py
  login: admin

- url: /stats_task
  script: stat_management.py
  login: admin

- url: /data_consolidation
  script: data_consolidation.py
  login: admin

- url: /article/(.*)
  script: articles.py

- url: /feed
  script: articles.py

- url: /callback
  script: phbb_callback.py

- url: /memcache_test
  script: cron.py
  login: admin

- url: /_ah/xmpp/message/chat/
  script: xmpp_handler.py

- url: /send_invite
  script: xmpp_handler.py

- url: /test_domains
  script: test_domains.py
  login: admin

- url: /aggregate_data
  script: data_consolidation.py
  login: admin

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /blog
  script: articles.py

- url: /user_consolidation
  script: data_consolidation.py
  #login: admin

- url: /user/.*
  script: users.py

- url: /.*
  script: main.py

inbound_services:
  - xmpp_message
