application: instaright
version: 55
runtime: python 
api_version: 1

handlers:
- url: /cron
  script: cron.py
  login: admin

- url: /account.*
  script: account.py

- url: /scripts
  static_dir: scripts

- url: /css
  static_dir: css

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /profiler/stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /visual
  script: visualization.py

- url: /stats
  script: stats.py
  login: admin

- url: /stats/.*
  script: stats.py
  login: admin

- url: /static
  static_dir: static

- url: /delete_stats
  script: stat_management.py
  login: admin

- url: /stats_task
  script: stat_management.py
#  login: admin

- url: /data_consolidation
  script: data_consolidation.py
#  login: admin

- url: /short_link_consolidation
  script: data_consolidation.py
#  login: admin

- url: /article/task
  script: main.py
  login: admin

- url: /article/(.*)
  script: articles.py

- url: /feed
  script: articles.py

- url: /callback
  script: pshb_callback.py

- url: /message/.*
  script: pshb_callback.py

- url: /memcache_test
  script: cron.py
  login: admin

- url: /_ah/xmpp/message/chat/
  script: xmpp_handler.py

- url: /send_invite
  script: xmpp_handler.py

- url: /test_domains
  script: test_domains.py
  login: admin

- url: /aggregate_data
  script: data_consolidation.py
  login: admin

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /oauth/.*
  script: lib/oauth_handler.py

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /blog
  script: articles.py

- url: /user_consolidation
  script: data_consolidation.py
  login: admin

- url: /user_consolidation_task
  script: data_consolidation.py
  login: admin

- url: /data_consolidation_task
  script: data_consolidation.py
  login: admin

- url: /feed_link_consolidation_task
  script: data_consolidation.py
  login: admin

- url: /short_link_consolidation_task
  script: data_consolidation.py
  login: admin

- url: /user/.*
  script: users.py
#  login: admin

- url: /link/add
  script: fetch/link_info.py

- url: /link/traction/task
  script: fetch/link_info.py

- url: /domain/categories.*
  script: links.py
  
- url: /category.*
  script: categories.py
  
- url: /link/category.*
  script: categories.py
  
- url: /link/.*
  script: links.py
  
- url: /util/.*
  script: social/social_activity.py

- url: /badges/.*
  script: badges.py

- url: /tools/delicious
  script: tools/fromdelicious.py
#  login: admin

- url: /tools/delicious/callback
  script: tools/fromdelicious.py

- url: /tools/import/instapaper/task
  script: tools/fromdelicious.py

- url: /tools/import/delicious
  script: tools/fromdelicious.py

- url: /tools/import/delicious/task
  script: tools/fromdelicious.py

- url: /tools/addon/instaright.xpi
  script: addon.py

- url: /test.*
  script: gaeunit.py

- url: /example
  script: example.py

- url: /.*
  script: main.py

inbound_services:
  - xmpp_message

admin_console:
 pages:
 - name: Appstats
   url: /profiler/stats
